### ISSUE TITLE
my code might help you figure out hot to reintegrate with the changes

### ISSUE THREAD

**Issue by Benjaneer** [for-the-new-order/storyteller-star-wars-theme#4]
https://github.com/Benjaneer/storyteller-addon-singlesheet

**Comment by Carl-Hugo** [comment]
> my code might help you figure out hot to reintegrate with the changes

Thanks for sharing. Next time I GM a Sci-fi game that could benefit from this theme and have some free time, I'll see if I can start from your code 😄 

EDIT: I don't know if I will invest time in this. Going from 6 lines of JS and a few lines of CSS to writing much more code feels too much for no gain. My implementation was hacky yet quick, and it worked. If I reopen this, I may extend the default journal entries instead of depending on a third-party module.

**Comment by Benjaneer** [comment]
fair enough :)
